projet_homepage:
    path:     /admin
    defaults: { _controller: ProjetBundle:Default:index }
Show_Activite:
    path:     /showactivite
    defaults: { _controller: ProjetBundle:Activite:show }
Add_Activite:
    path:     /addactivite
    defaults: { _controller: ProjetBundle:Activite:add }
delete_activite:
    path:     /deleteactivite/{qdt}
    defaults: { _controller: ProjetBundle:Activite:delete }
activite_edit:
    path:     /editactivite/{id}
    defaults: { _controller: ProjetBundle:Activite:edit }
Show_Classe:
    path:     /showclasse
    defaults: { _controller: ProjetBundle:Classe:show }
Add_Classe:
    path:     /addclasse
    defaults: { _controller: ProjetBundle:Classe:add }
delete_classe:
    path:     /deleteclasse/{qdt}
    defaults: { _controller: ProjetBundle:Classe:delete }
classe_edit:
    path:     /editclasse/{id}
    defaults: { _controller: ProjetBundle:Classe:edit }
graphePie:
    path: /chart
    defaults: { _controller: ProjetBundle:Classe:graph}
Show_ClasseMob:
    path:     /showclasseM
    defaults: { _controller: ProjetBundle:Classe:all }
newAction:
    path:     /new
    defaults: { _controller: ProjetBundle:Activite:new }
Show_AfficheMob:
    path:     /showclasseA
    defaults: { _controller: ProjetBundle:Activite:aff }

toPDF:
    path:     /pdf
    defaults: { _controller: ProjetBundle:Activite:toPDF }
frontClasse:
    path:     /frontClasse
    defaults: { _controller: ProjetBundle:Classe:frontClasse }
show_detailClasse:
    path:     /show_detailClasse/{id}
    defaults: { _controller: ProjetBundle:Classe:showdetailClasse }

#said (sante )
Show_Pediatre:
    path:     /showpediatre
    defaults: { _controller: ProjetBundle:Pediatre:show }
Add_Pediatre:
    path:     /addpediatre
    defaults: { _controller: ProjetBundle:Pediatre:add }
delete_pediatre:
    path:     /deletepediatre/{qdt}
    defaults: { _controller: ProjetBundle:Pediatre:delete }
pediatre_edit:
    path:     /editpediatre/{id}
    defaults: { _controller: ProjetBundle:Pediatre:edit }
Show_Profil:
    path:     /showprofil
    defaults: { _controller: ProjetBundle:Profilmedicale:show }
Add_Profil:
    path:     /addprofil
    defaults: { _controller: ProjetBundle:Profilmedicale:add }
delete_profil:
    path:     /deleteprofil/{qdt}
    defaults: { _controller: ProjetBundle:Profilmedicale:delete }
profil_edit:
    path:     /editprofil/{id}
    defaults: { _controller: ProjetBundle:Profilmedicale:edit }
show_detail:
    path:     /showdetail/{id}
    defaults: { _controller: ProjetBundle:Profilmedicale:showdetail }
projet_home:
    path:     /home
    defaults: { _controller: ProjetBundle:Default:Redirect }
show_front:
    path:     /showfront
    defaults: { _controller: ProjetBundle:Profilmedicale:showfront }
all:
    path:     /profilmedicale/all
    defaults: { _controller: ProjetBundle:Profilmedicale:all }
listes:
    path:     /profilmedicale/listes
    defaults: { _controller: ProjetBundle:Profilmedicale:listes }
login:
    path:     /profilmedicale/login/{username}/{password}
    defaults: { _controller: ProjetBundle:loginjson:login }
toPDFp:
    path:     /pdf/{id}
    defaults: { _controller: ProjetBundle:Profilmedicale:toPDF }
getOne:
    path:     /profilmedicale/getOne/{id}
    defaults: { _controller: ProjetBundle:Profilmedicale:getOne }
#mekki
club_ajout:
    path:     /ajout
    defaults: { _controller: ProjetBundle:Club:ajout }
club_delete:
    path:     /deleteC/{id}
    defaults: { _controller: ProjetBundle:Club:delete }
club_update:
    path:     /updateC/{id}
    defaults: { _controller: ProjetBundle:Club:update }
club_search:
    path:     /list
    defaults: { _controller: ProjetBundle:Club:search }
club_home:
    path:     /lists
    defaults: { _controller: ProjetBundle:Default:redirect }
media_ajout:
    path:     /ajoutmedia
    defaults: { _controller: ProjetBundle:Media:add }
media_affiche:
    path:     /affichemedia/{id}
    defaults: { _controller: ProjetBundle:Media:trouverId }
media_affiche_user:
    path:     /affichemediauser/{id}
    defaults: { _controller: ProjetBundle:Club:trouverId }
media_delete:
    path:     /deletemedia/{id}
    defaults: { _controller: ProjetBundle:Media:supprimer }
media_update:
    path:     /updatemedia/{id}
    defaults: { _controller: ProjetBundle:Media:modifier }
media_aff:
    path:     /affichemedia
    defaults: { _controller: ProjetBundle:Media:search }
club_subscription:
    path:     /subscription
    defaults: { _controller: ProjetBundle:Club:subscription }
###
user_club:
    path:     /user
    defaults: { _controller: ProjetBundle:Club:userdash }
admin_club:
    path:     /admin_user
    defaults: { _controller: ProjetBundle:Club:userdashb }
user_delete:
    path:     /deleteuser/{id}
    defaults: { _controller: ProjetBundle:Club:deleteuser }
user_delete1:
    path:     /deleteuserr/{id}
    defaults: { _controller: ProjetBundle:Club:deleteuserr }
club_user:
    path:     /affuser
    defaults: { _controller: ProjetBundle:Club:list }
Club_All:
    path:     /tasks
    defaults: { _controller: ProjetBundle:Club:all }
subscription_new:
    path:     /tasks/new
    defaults: { _controller: ProjetBundle:Club:new }
subscription_consult:
    path:     /tasks/club
    defaults: { _controller: ProjetBundle:Club:SubscriptionJson }
login_json:
    path:     /tasks/login/{username}/{password}
    defaults: { _controller: ProjetBundle:Loginjson:login }
Inscription_json:
    path:     /tasks/inscription
    defaults: { _controller: ProjetBundle:Club:Inscription }
json_delete:
    path:     /tasks/deleteuser/{id}
    defaults: { _controller: ProjetBundle:Club:SupprimerJson }
mobile_add:
    path:     /tasks/add/{id}
    defaults: { _controller: ProjetBundle:Club:InscriptionJson }
mobile_show_all_media:
    path:     /tasks/showall
    defaults: { _controller: ProjetBundle:Media:mobileAfficherAllMedia }
mobile_show_one_media:
    path:     /tasks/showone/{id}
    defaults: { _controller: ProjetBundle:Media:mobileAfficherOneMedia }
mobile_show_all_sub:
    path:     /tasks/showallsub
    defaults: { _controller: ProjetBundle:Club:mobileAfficherSub }
mobile_show_one_sub:
    path:     /tasks/showonesub/{id}
    defaults: { _controller: ProjetBundle:Club:mobileAfficheroneSub }
#mondher
evenement_home:
    path:     /event
    defaults: { _controller: ProjetBundle:Default:redirect }
evenement_Front:
    path:     /F
    defaults: { _controller: ProjetBundle:Evenement:Front }
evenement_AjoutE:
    path:     /AjoutE
    defaults: { _controller: ProjetBundle:Evenement:AjoutEvenement }
evenement_AfficherE:
    path:     /AfficheE
    defaults: { _controller: ProjetBundle:Evenement:AfficheEvenement }
evenement_AfficheP:
    path:     /AfficheP
    defaults: { _controller: ProjetBundle:Evenement:AfficheParticipant }
evenement_SupprimeP:
    path:     /SupprimeP/{id}
    defaults: { _controller: ProjetBundle:Evenement:SupprimeParticipant }
evenement_ModifieP:
    path:     /ModifieP/{id}
    defaults: { _controller: ProjetBundle:Evenement:ModifieParticipant }
evenement_AjoutP:
    path:     /AjoutP/{id}
    defaults: { _controller: ProjetBundle:Evenement:AjoutParticipant }
evenement_SupprimeE:
    path:     /SupprimeE/{id}
    defaults: { _controller: ProjetBundle:Evenement:SupprimeEvenement }
evenement_ModifierE:
    path:     /ModifieE/{id}
    defaults: { _controller: ProjetBundle:Evenement:ModifieEvenement }
evenement_RechercheE:
    path:     /RechercheE
    defaults: { _controller: ProjetBundle:Evenement:RechercheEvenement }
evenement_RechercheP:
    path:     /RechercheP
    defaults: { _controller: ProjetBundle:Evenement:RechercheParticipant }
evenement_Mail:
    path:     /mail
    defaults: { _controller: ProjetBundle:Evenement:Mail }

evenement_pdf:
    path:     /pdf
    defaults: { _controller: ProjetBundle:Default:pdf }
evenement_pdf1:
    path:     /pdf1
    defaults: { _controller: ProjetBundle:Default:pdf1 }


participant_AfficheE:
    path:     /fAfficheE
    defaults: { _controller: ProjetBundle:Participant:AfficheEvenement }
participant_RechercheE:
    path:     /fRechercheE
    defaults: { _controller: ProjetBundle:Participant:RechercheEvenement }
participant_AjoutP:
    path:     /fAjoutP/{id}
    defaults: { _controller: ProjetBundle:Participant:AjoutParticipant }
participant_form:
    path:     /form
    defaults: { _controller: ProjetBundle:Participant:form }
participant_Mail:
    path:     /mailP
    defaults: { _controller: ProjetBundle:Participant:Mail }



all_E:
    path:     /evenement/all
    defaults: { _controller: ProjetBundle:Evenement:all }
all_P:
    path:     /participant/all
    defaults: { _controller: ProjetBundle:Participant:all }
new:
    path:     /new/{id}
    defaults: { _controller: ProjetBundle:Evenement:new }
delete:
    path:     /deleteM
    defaults: { _controller: ProjetBundle:Evenement:delete }
edit:
    path:     /participant/edit
    defaults: { _controller: ProjetBundle:Evenement:edit }
all_Ev:
    path:     /evenement/alll
    defaults: { _controller: ProjetBundle:Participant:alll }

#login:
 #   path:     /loginM/{username}/{password}
  #  defaults: { _controller: AppBundle:Mobile:login }
#rchid
Ut_homepage:
    path:     /acceuil
    defaults: { _controller: ProjetBundle:Acceuil:index }
AD_homepage:
    path:     /admin
    defaults: { _controller: ProjetBundle:Acceuil:Admin }
Enfant_home:
    path:     /home
    defaults: { _controller: ProjetBundle:Default:redirect }
enfant_ajout:
    path:     /ajoutE
    defaults: { _controller: ProjetBundle:Enfant:ajout }
enfant_ajout_UT:
    path:     /ajoutUT
    defaults: { _controller: ProjetBundle:Enfant:ajoutUT }
enfant_search:
    path:     /table
    defaults: { _controller: ProjetBundle:Enfant:list }
enfant_search_UT:
    path:     /tableUT
    defaults: { _controller: ProjetBundle:Enfant:listUT }
enfant_delete:
    path:     /deleteE/{id}
    defaults: { _controller: ProjetBundle:Enfant:delete }
enfant_delete_UT:
    path:     /deleteUT/{id}
    defaults: { _controller: ProjetBundle:Enfant:deleteUT }
enfant_update:
    path:     /updateE/{id}
    defaults: { _controller: ProjetBundle:Enfant:update }
enfant_update_UT:
    path:     /updateUT/{id}
    defaults: { _controller: ProjetBundle:Enfant:updateUT }
EmploiDuTemps_ajout:
    path:     /ajoutEm
    defaults: { _controller: ProjetBundle:EmploiDuTemps:ajout }
EmploiDuTemps_search:
    path:     /tableEm
    defaults: { _controller: ProjetBundle:EmploiDuTemps:search }
EmploiDuTemps_search_UT:
    path:     /tableEmut
    defaults: { _controller: ProjetBundle:EmploiDuTemps:searchUT }
Afficher_Emploi:
    path:     /tableEmm
    defaults: { _controller: ProjetBundle:EmploiDuTemps:all}
Afficher_Emploi_Mobile:
    path:     /tableEmmobile
    defaults: { _controller: ProjetBundle:EmploiDuTemps:AfficherAllEmploi}
EmploiDuTemps_delete:
    path:     /deleteEm/{id}
    defaults: { _controller: ProjetBundle:EmploiDuTemps:delete }

EmploiDuTemps_update:
    path:     /updateEm/{id}
    defaults: { _controller: ProjetBundle:EmploiDuTemps:update }

Calendar_search:
    path:     /Calendrier
    defaults: { _controller: ProjetBundle:Calendrier:calendar }
Calendar_search_UT:
    path:     /CalendrierUT
    defaults: { _controller: ProjetBundle:Calendrier:calendarUT }

Enfant_All:
    path:     /enfantall
    defaults: { _controller: ProjetBundle:Enfant:all }
Enfant_Alll:
    path:     /taskss
    defaults: { _controller: ProjetBundle:LoginJson:ShowUsersMobile }

newenfant:
    path:     /enfant/new
    defaults: { _controller: ProjetBundle:Enfant:newenfant }

DeleteEnfantAction:
    path:     /enfant/DeleteEnfant/{id}
    defaults: { _controller: ProjetBundle:Enfant:DeleteEnfant }

ModifierEnfantAction:
    path:     /enfant/ModifierEnfant/{id}
    defaults: { _controller: ProjetBundle:Enfant:ModifierEnfant }
esprit_homepage:
    path:     /
    defaults: { _controller: ProjetBundle:Default:index }
    ##########
#jihed
