projet_homepage:
    path:     /admin
    defaults: { _controller: ProjetBundle:Default:index }
Show_Activite:
    path:     /showactivite
    defaults: { _controller: ProjetBundle:Activite:show }
Add_Activite:
    path:     /addactivite
    defaults: { _controller: ProjetBundle:Activite:add }
delete_activite:
    path:     /deleteactivite/{qdt}
    defaults: { _controller: ProjetBundle:Activite:delete }
activite_edit:
    path:     /editactivite/{id}
    defaults: { _controller: ProjetBundle:Activite:edit }
Show_Classe:
    path:     /showclasse
    defaults: { _controller: ProjetBundle:Classe:show }
Add_Classe:
    path:     /addclasse
    defaults: { _controller: ProjetBundle:Classe:add }
delete_classe:
    path:     /deleteclasse/{qdt}
    defaults: { _controller: ProjetBundle:Classe:delete }
classe_edit:
    path:     /editclasse/{id}
    defaults: { _controller: ProjetBundle:Classe:edit }
Show_Pediatre:
    path:     /showpediatre
    defaults: { _controller: ProjetBundle:Pediatre:show }
Add_Pediatre:
    path:     /addpediatre
    defaults: { _controller: ProjetBundle:Pediatre:add }
delete_pediatre:
    path:     /deletepediatre/{qdt}
    defaults: { _controller: ProjetBundle:Pediatre:delete }
pediatre_edit:
    path:     /editpediatre/{id}
    defaults: { _controller: ProjetBundle:Pediatre:edit }
Show_Profil:
    path:     /showprofil
    defaults: { _controller: ProjetBundle:Profilmedicale:show }
Add_Profil:
    path:     /addprofil
    defaults: { _controller: ProjetBundle:Profilmedicale:add }
delete_profil:
    path:     /deleteprofil/{qdt}
    defaults: { _controller: ProjetBundle:Profilmedicale:delete }
profil_edit:
    path:     /editprofil/{id}
    defaults: { _controller: ProjetBundle:Profilmedicale:edit }
show_detail:
    path:     /showdetail/{id}
    defaults: { _controller: ProjetBundle:Profilmedicale:showdetail }
projet_home:
    path:     /home
    defaults: { _controller: ProjetBundle:Default:Redirect }
show_front:
    path:     /showfront
    defaults: { _controller: ProjetBundle:Profilmedicale:showfront }
all:
    path:     /profilmedicale/all
    defaults: { _controller: ProjetBundle:Profilmedicale:all }
listes:
    path:     /profilmedicale/listes
    defaults: { _controller: ProjetBundle:Profilmedicale:listes }
login:
    path:     /profilmedicale/login/{username}/{password}
    defaults: { _controller: ProjetBundle:loginjson:login }
toPDF:
    path:     /pdf/{id}
    defaults: { _controller: ProjetBundle:Profilmedicale:toPDF }
getOne:
    path:     /profilmedicale/getOne/{id}
    defaults: { _controller: ProjetBundle:Profilmedicale:getOne }
#mekki
club_ajout:
    path:     /ajout
    defaults: { _controller: ProjetBundle:Club:ajout }
club_delete:
    path:     /delete/{id}
    defaults: { _controller: ProjetBundle:Club:delete }
club_update:
    path:     /update/{id}
    defaults: { _controller: ProjetBundle:Club:update }
club_search:
    path:     /list
    defaults: { _controller: ProjetBundle:Club:search }
club_home:
    path:     /lists
    defaults: { _controller: ProjetBundle:Default:redirect }
media_ajout:
    path:     /ajoutmedia
    defaults: { _controller: ProjetBundle:Media:add }
media_affiche:
    path:     /affichemedia/{id}
    defaults: { _controller: ProjetBundle:Media:trouverId }
media_affiche_user:
    path:     /affichemediauser/{id}
    defaults: { _controller: ProjetBundle:Club:trouverId }
media_delete:
    path:     /deletemedia/{id}
    defaults: { _controller: ProjetBundle:Media:supprimer }
media_update:
    path:     /updatemedia/{id}
    defaults: { _controller: ProjetBundle:Media:modifier }
media_aff:
    path:     /affichemedia
    defaults: { _controller: ProjetBundle:Media:search }
club_subscription:
    path:     /subscription
    defaults: { _controller: ProjetBundle:Club:subscription }
###
user_club:
    path:     /user
    defaults: { _controller: ProjetBundle:Club:userdash }
admin_club:
    path:     /admin_user
    defaults: { _controller: ProjetBundle:Club:userdashb }
user_delete:
    path:     /deleteuser/{id}
    defaults: { _controller: ProjetBundle:Club:deleteuser }
user_delete1:
    path:     /deleteuserr/{id}
    defaults: { _controller: ProjetBundle:Club:deleteuserr }
club_user:
    path:     /affuser
    defaults: { _controller: ProjetBundle:Club:list }
Club_All:
    path:     /tasks
    defaults: { _controller: ProjetBundle:Club:all }
subscription_new:
    path:     /tasks/new
    defaults: { _controller: ProjetBundle:Club:new }
subscription_consult:
    path:     /tasks/club
    defaults: { _controller: ProjetBundle:Club:SubscriptionJson }
login_json:
    path:     /tasks/login/{username}/{password}
    defaults: { _controller: ProjetBundle:Loginjson:login }
Inscription_json:
    path:     /tasks/inscription
    defaults: { _controller: ProjetBundle:Club:Inscription }
json_delete:
    path:     /tasks/deleteuser/{id}
    defaults: { _controller: ProjetBundle:Club:SupprimerJson }
mobile_add:
    path:     /tasks/add/{id}
    defaults: { _controller: ProjetBundle:Club:InscriptionJson }
mobile_show_all_media:
    path:     /tasks/showall
    defaults: { _controller: ProjetBundle:Media:mobileAfficherAllMedia }
mobile_show_one_media:
    path:     /tasks/showone/{id}
    defaults: { _controller: ProjetBundle:Media:mobileAfficherOneMedia }
mobile_show_all_sub:
    path:     /tasks/showallsub
    defaults: { _controller: ProjetBundle:Club:mobileAfficherSub }
mobile_show_one_sub:
    path:     /tasks/showonesub/{id}
    defaults: { _controller: ProjetBundle:Club:mobileAfficheroneSub }
