fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

projet:
    resource: "@ProjetBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
