<?php

namespace ProjetBundle\Repository;

/**
 * EmploiDuTempsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmploiDuTempsRepository extends \Doctrine\ORM\EntityRepository
{
}
