<?php

namespace ProjetBundle\Repository;

/**
 * MediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaRepository extends \Doctrine\ORM\EntityRepository
{
    function myfindid($id){
        $qb=$this->createQueryBuilder('c');
        $qb->where('c.Club= :Club');
        $qb->setParameter('Club',$id);
        $query=$qb->getQuery();
        return $query->getResult();
    }




}
