<?php

namespace ProjetBundle\Repository;

/**
 * PediatreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PediatreRepository extends \Doctrine\ORM\EntityRepository
{

}
