<?php

namespace ProjetBundle\Repository;

/**
 * ProfilmedicaleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfilmedicaleRepository extends \Doctrine\ORM\EntityRepository
{
    public function getListeP($id)
    {
        $qp= $this->createQueryBuilder('p')
            ->join('p.idpediatre', 'pm')
            ->where('pm.id=:query')
            ->setParameter('query',$id);
        return $qp ->getQuery()->getResult();
    }
}
